/* Generated by `npm run overview:links -w @os-community/shared` — do not edit. */
/* Canonical: packages/shared/src/brand-links.ts + overview-links.ts */
(function () {
  var LINKS = {
    "overview": "https://oorgos.org",
    "community": "https://community.oorgos.org",
    "consoleStart": "https://community.oorgos.org/ops/console/start?next=%2F"
  };
  window.OORGOS_LINKS = LINKS;
  var nodes = document.querySelectorAll("a[data-ecosystem-link]");
  for (var i = 0; i < nodes.length; i += 1) {
    var href = LINKS[nodes[i].getAttribute("data-ecosystem-link")];
    if (href) nodes[i].setAttribute("href", href);
  }
})();
