#!/usr/bin/env node
/**
 * Builds pre-merged locale bundles from English canonical JSON + locale overrides.
 * Output: packages/shared/src/i18n/generated/bundles.ts
 */
import fs from "node:fs";
import {
  GENERATED_DIR,
  LOCALES,
  NAMESPACES,
  assertJaLocaleCopyClean,
  loadAllLocales,
  namespacePath,
  readJsonFile,
  toTsLiteral,
} from "./lib.mjs";

for (const namespace of NAMESPACES) {
  assertJaLocaleCopyClean(namespace, readJsonFile(namespacePath(namespace, "ja")));
}

const coreByLocale = loadAllLocales("core");
const pagesByLocale = loadAllLocales("pages");
const labelsByLocale = loadAllLocales("labels");
const formsByLocale = loadAllLocales("forms");
const userPagesByLocale = loadAllLocales("user-pages");
const opennessByLocale = loadAllLocales("openness-policy");
const errorsByLocale = loadAllLocales("errors");

/** @type {Record<string, unknown>} */
const messagesByLocale = {};
for (const locale of LOCALES) {
  messagesByLocale[locale] = {
    ...(coreByLocale[locale]),
    opennessPolicy: opennessByLocale[locale],
    userPages: userPagesByLocale[locale],
  };
}

const header = `/* eslint-disable */
/** AUTO-GENERATED by scripts/i18n/build-i18n.mjs — do not edit. */
import type { Locale, UiReadyLocale } from "../locales";
import type { Messages } from "../types/messages";
import type { PageMessages } from "../types/pages";
import type { LabelMessages } from "../types/labels";
import type { FormMessages } from "../types/forms";
import type { UserPagesMessages } from "../types/user-pages";
import type { OpennessPolicyMessages } from "../types/openness-policy";

export const MESSAGES: Record<UiReadyLocale, Messages> = ${toTsLiteral(messagesByLocale)} as Record<UiReadyLocale, Messages>;

export const PAGE_MESSAGES: Record<UiReadyLocale, PageMessages> = ${toTsLiteral(pagesByLocale)} as Record<UiReadyLocale, PageMessages>;

export const LABEL_MESSAGES: Record<UiReadyLocale, LabelMessages> = ${toTsLiteral(labelsByLocale)} as Record<UiReadyLocale, LabelMessages>;

export const FORM_MESSAGES: Record<UiReadyLocale, FormMessages> = ${toTsLiteral(formsByLocale)} as Record<UiReadyLocale, FormMessages>;

export const ERROR_MESSAGES: Record<UiReadyLocale, Record<string, string>> = ${toTsLiteral(errorsByLocale)} as Record<UiReadyLocale, Record<string, string>>;

export function getErrorMessage(locale: Locale, code: string): string {
  const bundle = ERROR_MESSAGES[locale] ?? ERROR_MESSAGES.en;
  return bundle[code] ?? ERROR_MESSAGES.en[code] ?? code;
}
`;

fs.mkdirSync(GENERATED_DIR, { recursive: true });
fs.writeFileSync(`${GENERATED_DIR}/bundles.ts`, header, "utf8");

console.log(`Generated ${GENERATED_DIR}/bundles.ts (${LOCALES.length} locales, ${NAMESPACES.length} namespaces)`);
