import type { Locale } from "./i18n/locales";
import type { LocalizedStrings } from "./i18n/locales";
import { getLocalized } from "./i18n/index";
import { localized } from "./i18n/localized";
import { BRAND_LINKS } from "./brand-links";

export type FooterLink = {
  href: string;
  label: LocalizedStrings;
  external?: boolean;
};

export type FooterColumn = {
  id: string;
  title: LocalizedStrings;
  links: FooterLink[];
};

/** Linux Foundation 左カラム — About the OOS ナビ */
export const FOOTER_ABOUT_LINKS: FooterLink[] = [
  {
    href: "/about",
    label: localized({
      en: "About OpenOrgOS",
      ja: "OpenOrgOS について",
      pt: "Sobre o OpenOrgOS",
      es: "Acerca de OpenOrgOS",
      et: "OpenOrgOS-ist",
      fr: "À propos d'OpenOrgOS",
      zh: "关于 OpenOrgOS",
      de: "Über OpenOrgOS",
      ru: "Об OpenOrgOS",
    }),
  },
  {
    href: "/about/leadership",
    label: localized({
      en: "Leadership",
      ja: "リーダーシップ",
      pt: "Liderança",
      es: "Liderazgo",
      et: "Juhtimine",
      fr: "Direction",
      zh: "领导层",
      de: "Führung",
      ru: "Руководство",
    }),
  },
  {
    href: "/about/careers",
    label: localized({
      en: "Careers",
      ja: "コントリビュート",
      pt: "Contribuir",
      es: "Contribuir",
      et: "Panustamine",
      fr: "Contribuer",
      zh: "参与贡献",
      de: "Mitwirken",
      ru: "Участие",
    }),
  },
  {
    href: "/members",
    label: localized({
      en: "Corporate Members",
      ja: "コーポレートメンバー",
      pt: "Membros corporativos",
      es: "Miembros corporativos",
      et: "Ettevõtte liikmed",
      fr: "Membres corporatifs",
      zh: "企业成员",
      de: "Unternehmensmitglieder",
      ru: "Корпоративные члены",
    }),
  },
  {
    href: "/about/memberships",
    label: localized({
      en: "Membership Program",
      ja: "メンバーシップ",
      pt: "Programa de membros",
      es: "Programa de membresía",
      et: "Liikmelisus",
      fr: "Programme d'adhésion",
      zh: "会员计划",
      de: "Mitgliedschaft",
      ru: "Членство",
    }),
  },
  {
    href: "/about/supporters",
    label: localized({
      en: "Individual Supporters",
      ja: "個人サポーター",
      pt: "Apoiadores individuais",
      es: "Partidarios individuales",
      et: "Üksiktoetajad",
      fr: "Supporters individuels",
      zh: "个人支持者",
      de: "Einzelunterstützer",
      ru: "Индивидуальные сторонники",
    }),
  },
  {
    href: "/about/inclusion",
    label: localized({
      en: "Inclusion & Accessibility",
      ja: "インクルージョン & アクセシビリティ",
      pt: "Inclusão e acessibilidade",
      es: "Inclusión y accesibilidad",
      et: "Kaasatus ja ligipääsetavus",
      fr: "Inclusion et accessibilité",
      zh: "包容性与无障碍",
      de: "Inklusion & Barrierefreiheit",
      ru: "Инклюзивность и доступность",
    }),
  },
  {
    href: "/about/brand",
    label: localized({
      en: "OpenOrgOS Brand Guidelines",
      ja: "OpenOrgOS ブランドガイドライン",
      pt: "Diretrizes de marca OpenOrgOS",
      es: "Directrices de marca OpenOrgOS",
      et: "OpenOrgOS brändi juhised",
      fr: "Charte graphique OpenOrgOS",
      zh: "OpenOrgOS 品牌指南",
      de: "OpenOrgOS Markenrichtlinien",
      ru: "Руководство по бренду OpenOrgOS",
    }),
  },
  {
    href: "/about/contact",
    label: localized({
      en: "Contact Us",
      ja: "お問い合わせ",
      pt: "Fale conosco",
      es: "Contáctenos",
      et: "Võtke meiega ühendust",
      fr: "Nous contacter",
      zh: "联系我们",
      de: "Kontakt",
      ru: "Связаться с нами",
    }),
  },
  {
    href: "/site-map",
    label: localized({
      en: "Site Map",
      ja: "サイトマップ",
      pt: "Mapa do site",
      es: "Mapa del sitio",
      et: "Saidikaart",
      fr: "Plan du site",
      zh: "网站地图",
      de: "Sitemap",
      ru: "Карта сайта",
    }),
  },
  {
    href: BRAND_LINKS.store,
    external: true,
    label: localized({
      en: "Store",
      ja: "ストア",
      pt: "Loja",
      es: "Tienda",
      et: "Pood",
      fr: "Boutique",
      zh: "商店",
      de: "Shop",
      ru: "Магазин",
    }),
  },
];

/** Linux Foundation フッター右カラム — OpenOrgOS にマッピング */
export const FOOTER_COLUMNS: FooterColumn[] = [
  {
    id: "projects",
    title: localized({
      en: "PROJECTS",
      ja: "PROJECTS",
      pt: "PROJETOS",
      es: "PROYECTOS",
      et: "PROJEKTID",
      fr: "PROJETS",
      zh: "PROJECTS",
      de: "PROJEKTE",
      ru: "ПРОЕКТЫ",
    }),
    links: [
      {
        href: "/modules",
        label: localized({
          en: "View All Modules",
          ja: "すべてのモジュール",
          pt: "Ver todos os módulos",
          es: "Ver todos los módulos",
          et: "Vaata kõiki mooduleid",
          fr: "Voir tous les modules",
          zh: "查看所有模块",
          de: "Alle Module anzeigen",
          ru: "Все модули",
        }),
      },
      {
        href: "/wild-modules/register",
        label: localized({
          en: "Host Your Module",
          ja: "モジュールをホスト",
          pt: "Hospedar seu módulo",
          es: "Alojar su módulo",
          et: "Mooduli hostimine",
          fr: "Héberger votre module",
          zh: "托管您的模块",
          de: "Modul hosten",
          ru: "Разместить модуль",
        }),
      },
      {
        href: "/about/partners",
        label: localized({
          en: "Partner Program",
          ja: "パートナープログラム",
          pt: "Programa de parceiros",
          es: "Programa de socios",
          et: "Partnerlusprogramm",
          fr: "Programme partenaires",
          zh: "合作伙伴计划",
          de: "Partnerprogramm",
          ru: "Партнёрская программа",
        }),
      },
      {
        href: "/standards",
        label: localized({
          en: "Security",
          ja: "セキュリティ",
          pt: "Segurança",
          es: "Seguridad",
          et: "Turvalisus",
          fr: "Sécurité",
          zh: "安全",
          de: "Sicherheit",
          ru: "Безопасность",
        }),
      },
      {
        href: "/standards",
        label: localized({
          en: "Standards and Specifications",
          ja: "標準と仕様",
          pt: "Padrões e especificações",
          es: "Estándares y especificaciones",
          et: "Standardid ja spetsifikatsioonid",
          fr: "Normes et spécifications",
          zh: "标准与规范",
          de: "Standards und Spezifikationen",
          ru: "Стандарты и спецификации",
        }),
      },
      {
        href: "/governance",
        label: localized({
          en: "Digital Trust",
          ja: "デジタルトラスト",
          pt: "Confiança digital",
          es: "Confianza digital",
          et: "Digitaalne usaldus",
          fr: "Confiance numérique",
          zh: "数字信任",
          de: "Digitales Vertrauen",
          ru: "Цифровое доверие",
        }),
      },
      {
        href: "/about",
        label: localized({
          en: "Sustainability",
          ja: "サステナビリティ",
          pt: "Sustentabilidade",
          es: "Sostenibilidad",
          et: "Jätkusuutlikkus",
          fr: "Durabilité",
          zh: "可持续性",
          de: "Nachhaltigkeit",
          ru: "Устойчивое развитие",
        }),
      },
      {
        href: "/governance",
        label: localized({
          en: "Management & Best Practices",
          ja: "管理とベストプラクティス",
          pt: "Gestão e melhores práticas",
          es: "Gestión y mejores prácticas",
          et: "Juhtimine ja parimad tavad",
          fr: "Gestion et bonnes pratiques",
          zh: "管理与最佳实践",
          de: "Management & Best Practices",
          ru: "Управление и лучшие практики",
        }),
      },
    ],
  },
  {
    id: "resources",
    title: localized({
      en: "RESOURCES",
      ja: "RESOURCES",
      pt: "RECURSOS",
      es: "RECURSOS",
      et: "RESSURSSID",
      fr: "RESSOURCES",
      zh: "RESOURCES",
      de: "RESSOURCEN",
      ru: "РЕСУРСЫ",
    }),
    links: [
      {
        href: "/resources/blog",
        label: localized({
          en: "Blog",
          ja: "ブログ",
          pt: "Blog",
          es: "Blog",
          et: "Blogi",
          fr: "Blog",
          zh: "博客",
          de: "Blog",
          ru: "Блог",
        }),
      },
      {
        href: "/resources/publications",
        label: localized({
          en: "Publications",
          ja: "出版物",
          pt: "Publicações",
          es: "Publicaciones",
          et: "Väljaanded",
          fr: "Publications",
          zh: "出版物",
          de: "Publikationen",
          ru: "Публикации",
        }),
      },
      {
        href: "/resources/guides",
        label: localized({
          en: "Open Source Guides",
          ja: "オープンソースガイド",
          pt: "Guias de código aberto",
          es: "Guías de código abierto",
          et: "Avatud lähtekoodi juhendid",
          fr: "Guides open source",
          zh: "开源指南",
          de: "Open-Source-Leitfäden",
          ru: "Руководства по open source",
        }),
      },
      {
        href: "/learn",
        label: localized({
          en: "Webinars",
          ja: "ウェビナー / ビデオ",
          pt: "Webinars",
          es: "Seminarios web",
          et: "Veebiseminarid",
          fr: "Webinaires",
          zh: "网络研讨会 / 视频",
          de: "Webinare",
          ru: "Вебинары",
        }),
      },
      {
        href: "/resources/case-studies",
        label: localized({
          en: "Case Studies",
          ja: "事例紹介",
          pt: "Estudos de caso",
          es: "Casos de estudio",
          et: "Juhtumiuuringud",
          fr: "Études de cas",
          zh: "案例研究",
          de: "Fallstudien",
          ru: "Кейсы",
        }),
      },
    ],
  },
  {
    id: "newsroom",
    title: localized({
      en: "NEWSROOM",
      ja: "NEWSROOM",
      pt: "SALA DE IMPRENSA",
      es: "SALA DE PRENSA",
      et: "UUDISTETOIM",
      fr: "SALLE DE PRESSE",
      zh: "NEWSROOM",
      de: "NEWSROOM",
      ru: "ПРЕСС-ЦЕНТР",
    }),
    links: [
      {
        href: "/newsroom",
        label: localized({
          en: "Newsroom Home",
          ja: "Newsroom ホーム",
          pt: "Início da sala de imprensa",
          es: "Inicio de sala de prensa",
          et: "Uudistetoa avaleht",
          fr: "Accueil salle de presse",
          zh: "新闻中心首页",
          de: "Newsroom Start",
          ru: "Пресс-центр",
        }),
      },
      {
        href: "/newsroom/press-releases",
        label: localized({
          en: "Press Releases",
          ja: "プレスリリース",
          pt: "Comunicados de imprensa",
          es: "Comunicados de prensa",
          et: "Pressiteated",
          fr: "Communiqués de presse",
          zh: "新闻稿",
          de: "Pressemitteilungen",
          ru: "Пресс-релизы",
        }),
      },
      {
        href: "/newsroom/media-contacts",
        label: localized({
          en: "Media Contacts",
          ja: "メディア向け連絡先",
          pt: "Contactos de imprensa",
          es: "Contactos de prensa",
          et: "Meediakontaktid",
          fr: "Contacts presse",
          zh: "媒体联系",
          de: "Medienkontakte",
          ru: "Контакты для СМИ",
        }),
      },
    ],
  },
  {
    id: "research",
    title: localized({
      en: "OPENORGOS RESEARCH",
      ja: "OPENORGOS RESEARCH",
      pt: "OPENORGOS RESEARCH",
      es: "OPENORGOS RESEARCH",
      et: "OPENORGOS RESEARCH",
      fr: "OPENORGOS RESEARCH",
      zh: "OPENORGOS RESEARCH",
      de: "OPENORGOS RESEARCH",
      ru: "OPENORGOS RESEARCH",
    }),
    links: [
      {
        href: "/research",
        label: localized({
          en: "Latest Research",
          ja: "最新リサーチ",
          pt: "Pesquisa mais recente",
          es: "Investigación más reciente",
          et: "Viimased uuringud",
          fr: "Dernières recherches",
          zh: "最新研究",
          de: "Aktuelle Forschung",
          ru: "Последние исследования",
        }),
      },
      {
        href: "/committees",
        label: localized({
          en: "Leadership & Advisory Board",
          ja: "リーダーシップ & アドバイザリーボード",
          pt: "Liderança e conselho consultivo",
          es: "Liderazgo y consejo asesor",
          et: "Juhtimine ja nõuandekogu",
          fr: "Direction et conseil consultatif",
          zh: "领导层与顾问委员会",
          de: "Führung & Beirat",
          ru: "Руководство и консультативный совет",
        }),
      },
      {
        href: "/about/contact",
        label: localized({
          en: "Sponsor a Study",
          ja: "リサーチスポンサー",
          pt: "Patrocinar estudo",
          es: "Patrocinar estudio",
          et: "Uuringu sponsorlus",
          fr: "Sponsoriser une étude",
          zh: "赞助研究",
          de: "Studie sponsern",
          ru: "Спонсировать исследование",
        }),
      },
      {
        href: "/committees",
        label: localized({
          en: "Research Forum",
          ja: "リサーチフォーラム",
          pt: "Fórum de pesquisa",
          es: "Foro de investigación",
          et: "Teadusfoorum",
          fr: "Forum de recherche",
          zh: "研究论坛",
          de: "Forschungsforum",
          ru: "Исследовательский форум",
        }),
      },
    ],
  },
  {
    id: "education",
    title: localized({
      en: "OPENORGOS EDUCATION",
      ja: "OPENORGOS EDUCATION",
      pt: "OPENORGOS EDUCATION",
      es: "OPENORGOS EDUCATION",
      et: "OPENORGOS EDUCATION",
      fr: "OPENORGOS EDUCATION",
      zh: "OPENORGOS EDUCATION",
      de: "OPENORGOS EDUCATION",
      ru: "OPENORGOS EDUCATION",
    }),
    links: [
      {
        href: "/academy",
        label: localized({
          en: "Home",
          ja: "ホーム",
          pt: "Início",
          es: "Inicio",
          et: "Avaleht",
          fr: "Accueil",
          zh: "首页",
          de: "Startseite",
          ru: "Главная",
        }),
      },
      {
        href: "/academy",
        label: localized({
          en: "Course Catalog",
          ja: "コースカタログ",
          pt: "Catálogo de cursos",
          es: "Catálogo de cursos",
          et: "Kursuste kataloog",
          fr: "Catalogue de cours",
          zh: "课程目录",
          de: "Kurskatalog",
          ru: "Каталог курсов",
        }),
      },
      {
        href: "/learn",
        label: localized({
          en: "Resources",
          ja: "リソース",
          pt: "Recursos",
          es: "Recursos",
          et: "Ressursid",
          fr: "Ressources",
          zh: "资源",
          de: "Ressourcen",
          ru: "Ресурсы",
        }),
      },
      {
        href: "/certifications",
        label: localized({
          en: "Certification",
          ja: "認証制度",
          pt: "Certificação",
          es: "Certificación",
          et: "Sertifitseerimine",
          fr: "Certification",
          zh: "认证制度",
          de: "Zertifizierung",
          ru: "Сертификация",
        }),
      },
    ],
  },
  {
    id: "events",
    title: localized({
      en: "OPENORGOS EVENTS",
      ja: "OPENORGOS EVENTS",
      pt: "OPENORGOS EVENTS",
      es: "OPENORGOS EVENTS",
      et: "OPENORGOS EVENTS",
      fr: "OPENORGOS EVENTS",
      zh: "OPENORGOS EVENTS",
      de: "OPENORGOS EVENTS",
      ru: "OPENORGOS EVENTS",
    }),
    links: [
      {
        href: "/events",
        label: localized({
          en: "Home",
          ja: "ホーム",
          pt: "Início",
          es: "Inicio",
          et: "Avaleht",
          fr: "Accueil",
          zh: "首页",
          de: "Startseite",
          ru: "Главная",
        }),
      },
      {
        href: "/events/sponsor",
        label: localized({
          en: "Sponsor",
          ja: "スポンサー",
          pt: "Patrocinar",
          es: "Patrocinar",
          et: "Sponsoreerimine",
          fr: "Sponsoriser",
          zh: "赞助",
          de: "Sponsoring",
          ru: "Спонсорство",
        }),
      },
      {
        href: "/events/submit-talk",
        label: localized({
          en: "Submit a Talk",
          ja: "トークを提案",
          pt: "Enviar uma palestra",
          es: "Enviar una charla",
          et: "Esita ettekande ettepanek",
          fr: "Proposer une intervention",
          zh: "提交演讲",
          de: "Vortrag einreichen",
          ru: "Подать доклад",
        }),
      },
      {
        href: "/legal/terms",
        label: localized({
          en: "Code of Conduct",
          ja: "行動規範",
          pt: "Código de conduta",
          es: "Código de conducta",
          et: "Käitumisjuhend",
          fr: "Code de conduite",
          zh: "行为准则",
          de: "Verhaltenskodex",
          ru: "Кодекс поведения",
        }),
      },
    ],
  },
  {
    id: "platform",
    title: localized({
      en: "COMMUNITY PLATFORM",
      ja: "COMMUNITY PLATFORM",
      pt: "PLATAFORMA DA COMUNIDADE",
      es: "PLATAFORMA COMUNITARIA",
      et: "KOGUKONNA PLATVORM",
      fr: "PLATEFORME COMMUNAUTAIRE",
      zh: "COMMUNITY PLATFORM",
      de: "COMMUNITY-PLATTFORM",
      ru: "ПЛАТФОРМА СООБЩЕСТВА",
    }),
    links: [
      {
        href: "/",
        label: localized({
          en: "Platform Home",
          ja: "プラットフォーム ホーム",
          pt: "Página inicial da plataforma",
          es: "Inicio de la plataforma",
          et: "Platvormi avaleht",
          fr: "Accueil de la plateforme",
          zh: "平台首页",
          de: "Plattform-Startseite",
          ru: "Главная платформы",
        }),
      },
      {
        href: "/github",
        label: localized({
          en: "GitHub Tools",
          ja: "GitHub ツール",
          pt: "Ferramentas GitHub",
          es: "Herramientas GitHub",
          et: "GitHubi tööriistad",
          fr: "Outils GitHub",
          zh: "GitHub 工具",
          de: "GitHub-Tools",
          ru: "Инструменты GitHub",
        }),
      },
      {
        href: "/modules",
        label: localized({
          en: "Module Insights",
          ja: "モジュールインサイト",
          pt: "Insights de módulos",
          es: "Información de módulos",
          et: "Moodulite ülevaated",
          fr: "Analyses des modules",
          zh: "模块洞察",
          de: "Modul-Einblicke",
          ru: "Аналитика модулей",
        }),
      },
      {
        href: "/login",
        label: localized({
          en: "Create an Account",
          ja: "アカウント作成",
          pt: "Criar uma conta",
          es: "Crear una cuenta",
          et: "Loo konto",
          fr: "Créer un compte",
          zh: "创建账户",
          de: "Konto erstellen",
          ru: "Создать аккаунт",
        }),
      },
    ],
  },
];

export function getFooterAboutLinks(locale: Locale) {
  return FOOTER_ABOUT_LINKS.map((l) => ({
    href: l.href,
    label: getLocalized(l.label, locale),
    external: l.external ?? l.href.startsWith("http"),
  }));
}

export function getFooterColumns(locale: Locale) {
  return FOOTER_COLUMNS.map((col) => ({
    id: col.id,
    title: getLocalized(col.title, locale),
    links: col.links.map((l) => ({
      href: l.href,
      label: getLocalized(l.label, locale),
      external: l.external ?? l.href.startsWith("http"),
    })),
  }));
}
