import { BRAND_LINKS } from "./brand-links";

/** Community route that mints the Operator Console SSO handoff. */
export const CONSOLE_START_PATHNAME = "/ops/console/start";

/** `/ops/console/start?next=…` — shared by Community, the overview site, and Console. */
export function consoleStartQueryPath(next = "/"): string {
  return `${CONSOLE_START_PATHNAME}?next=${encodeURIComponent(next)}`;
}

/**
 * Cross-surface links for the static overview site (oorgos.org).
 * Console login always starts at Community — never at the Console origin.
 */
export type OverviewLinks = {
  overview: string;
  community: string;
  consoleStart: string;
};

export function overviewLinks(): OverviewLinks {
  return {
    overview: BRAND_LINKS.overview,
    community: BRAND_LINKS.community,
    consoleStart: `${BRAND_LINKS.community}${consoleStartQueryPath("/")}`,
  };
}

export const OVERVIEW_LINKS_FILENAME = "ecosystem-links.js";

/**
 * Static asset for `sites/coming-soon`. HTML keeps the same href as a no-JS
 * fallback; this script re-applies the canonical value at runtime.
 */
export function renderOverviewLinksScript(): string {
  const links = overviewLinks();
  return `/* Generated by \`npm run overview:links -w @os-community/shared\` — do not edit. */
/* Canonical: packages/shared/src/brand-links.ts + overview-links.ts */
(function () {
  var LINKS = ${JSON.stringify(links, null, 2).replace(/\n/g, "\n  ")};
  window.OORGOS_LINKS = LINKS;
  var nodes = document.querySelectorAll("a[data-ecosystem-link]");
  for (var i = 0; i < nodes.length; i += 1) {
    var href = LINKS[nodes[i].getAttribute("data-ecosystem-link")];
    if (href) nodes[i].setAttribute("href", href);
  }
})();
`;
}
