import {
  COMMUNITY_LOCALE_COOKIE,
  LOCALE_COOKIE_MAX_AGE,
  OORGOS_UI_LOCALE_COOKIE,
} from "./locale-bridge";

export const OVERVIEW_LOCALE_FILENAME = "locale-bridge.js";

/**
 * Static asset for `sites/coming-soon`.
 *
 * The overview site renders more locales than the Console UI, so only the
 * ja/en value goes into the `Domain=.oorgos.org` cookie. The full page locale
 * stays in this origin's localStorage, which never reaches Community.
 */
export function renderOverviewLocaleScript(): string {
  return `/* Generated by \`npm run overview:links -w @os-community/shared\` — do not edit. */
/* Canonical: packages/shared/src/locale-bridge.ts + overview-locale-script.ts */
(function () {
  var SHARED = ${JSON.stringify(OORGOS_UI_LOCALE_COOKIE)};
  var PAGE = ${JSON.stringify(COMMUNITY_LOCALE_COOKIE)};
  var MAX_AGE = ${LOCALE_COOKIE_MAX_AGE};

  /** Console UI has ja/en only. */
  function uiLocale(lang) {
    return lang === "ja" ? "ja" : "en";
  }

  function readCookie(name) {
    try {
      var m = document.cookie.match(
        new RegExp("(?:^|; )" + name.replace(/[.*+?^\${}()|[\\]\\\\]/g, "\\\\$&") + "=([^;]*)")
      );
      return m ? decodeURIComponent(m[1]) : null;
    } catch (e) {
      return null;
    }
  }

  function readStorage(key) {
    try {
      return window.localStorage.getItem(key);
    } catch (e) {
      return null;
    }
  }

  function write(lang) {
    var shared = uiLocale(lang);
    try {
      window.localStorage.setItem(PAGE, lang);
      window.localStorage.setItem(SHARED, shared);
    } catch (e) {}
    try {
      var host = location.hostname.toLowerCase();
      var parts = [
        SHARED + "=" + encodeURIComponent(shared),
        "path=/",
        "max-age=" + MAX_AGE,
        "SameSite=Lax"
      ];
      if (host === "oorgos.org" || host.endsWith(".oorgos.org")) {
        parts.push("Domain=.oorgos.org");
      }
      if (location.protocol === "https:") parts.push("Secure");
      document.cookie = parts.join(";");
    } catch (e) {}
  }

  /** Page locale wins over the shared ja/en value so non-ja/en choices stick. */
  function detect(supported) {
    var candidates = [
      readStorage(PAGE),
      readCookie(SHARED),
      readStorage(SHARED)
    ];
    for (var i = 0; i < candidates.length; i += 1) {
      if (candidates[i] && supported.indexOf(candidates[i]) !== -1) return candidates[i];
    }
    var browser = (navigator.language || "").toLowerCase();
    for (var j = 0; j < supported.length; j += 1) {
      if (browser.indexOf(supported[j]) === 0) return supported[j];
    }
    return supported[0];
  }

  window.OORGOS_LOCALE = { uiLocale: uiLocale, write: write, detect: detect };
})();
`;
}
